version: 2
registries:
  maven-central:
    type: maven-repository
    url: https://repo.maven.apache.org/maven2
  gradle-plugin-portal:
    type: maven-repository
    url: https://plugins.gradle.org/m2
  vividus-maven-registry:
    type: maven-repository
    url: https://maven.pkg.github.com/vividus-framework/vividus
    username: token
    password: ${{secrets.TOKEN_FOR_VIVIDUS_PACKAGE_REGISTRY}}
updates:
- package-ecosystem: gradle
  directory: /
  registries: "*"
  schedule:
    interval: weekly
- package-ecosystem: gitsubmodule
  directory: /
  schedule:
    interval: weekly
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: weekly
